name: 🐞 Bug
description: Report a bug or an issue found.
title: "[Bug] <title>"
labels: ["bug"]
body:

  - type: markdown
    attributes:
      value: |
        So you found something that's not quite right?

  - type: textarea
    attributes:
      label: Current Behavior
      description: What have you found; give a description of what is currently happening.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        If applicable, log output to help explain your problem.
      render: shell
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should be happening; give a description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Changes Needed
      description: What needs to be changed; give a description of what corrections need to be made.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Location of Issue
      description: Which files do you know to be involved in this issue?
    validations:
        required: true

  - type: textarea
    attributes:
      label: Code Snippets
      description: |
        This is a good place to include any relevant code snippets.
      render: sql
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
