name: 🚀 Feature
description: Request new features or changes to existing functionality.
title: "[Feature] <title>"
labels: ["enhancement"]
body:

  - type: markdown
    attributes:
      value: |
        You have an idea for a new feature, or a change to an existing functionality?

  - type: textarea
    attributes:
      label: Feature Description
      description: Some information regarding the changes to be added.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reason for Change
      description: What will this change enable, improve, or provide?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Where are the changes needed?
      description: Which files would be getting changed?
    validations:
        required: true

  - type: textarea
    attributes:
      label: Code Snippets
      description: |
        This is a good place to include any relevant code snippets.
      render: javascript
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything Else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
      
