# As of August 2023, SonarCloud does not support analysis of code from external pull request
# (e.g. from forks). This convoluted GitHub Action, and its companion `sonarcloud.yml`, is a
# workaround. The ‘SonarCloud’ GitHub Action defined in `sonarcloud.yml` runs upon the
# completion of this one.
#
# Adapted from:
# - https://github.com/se310-Team4/KKDZ/blob/release-2.0/.github/workflows/build.yml; and
# - https://community.sonarsource.com/t/how-to-use-sonarcloud-with-a-forked-repository-on-github/7363

name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: 🔢 Use Node.js version 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: 📶 Install dependencies
        run: pnpm install

      # - name: 🧪 Test
      #   run: |
      #     npm run test:ci
      #     cat ./coverage/lcov.info
      #
      # - name: 🔊 Upload code coverage to GitHub Artifacts (for SonarCloud)
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: typefaceoff-lcov-file
      #     path: coverage/lcov.info

      - name: 🔧 Build
        run: NODE_ENV=production npm run build

      - name: Lint
        run: pnpm run lint

      - name: Check formatting
        run: pnpm prettier --check .

      - name: 🔊 Save PR number (for SonarCloud)
        if: github.event_name == 'pull_request'
        run: echo ${{ github.event.number }} > PR_NUMBER.txt

      - name: 🔊 Upload PR number to GitHub Artifacts (for SonarCloud)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: PR_NUMBER
          path: PR_NUMBER.txt
